server:
  port: ${MUSEUM_PORT:8080}
  servlet:
    context-path: /museum
spring:
  application:
    name: museum
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_MYSQL_URL:jdbc:mysql://localhost:3306/museum}
    username: ${DB_MYSQL_USERNAME:root}
    password: ${DB_MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
jwt:
  secret: ${JWT_SECRET:JWT_SECRET_KEY_MUST_BE_32_DIGITS}
  expiration-minutes: 30
  expiration-day: 90
config:
  admin:
    name: ${ADMIN_NAME:adminadmin}
    password: ${ADMIN_PASSWORD:adminadmin@123}
    email: ${ADMIN_EMAIL:adminadmin@blwsmartware.net}
    username: ${ADMIN_USERNAME:adminadmin}
springdoc:
  swagger-ui:
    path: /swagger-ui.html